# Generated by Django 6.0.4 on 2026-04-29 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0003_perimetre_efficiance_reseau'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barrageretenue',
            name='date_diagnostic',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='barrageretenue',
            name='defaut_ouvrage',
            field=models.TextField(blank=True, default='', help_text='Texte libre sur les défauts observés'),
        ),
        migrations.AddField(
            model_name='barrageretenue',
            name='saisi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_saisis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barrageretenue',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foragepuits',
            name='date_diagnostic',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='foragepuits',
            name='defaut_ouvrage',
            field=models.TextField(blank=True, default='', help_text='Texte libre sur les défauts observés'),
        ),
        migrations.AddField(
            model_name='foragepuits',
            name='saisi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_saisis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foragepuits',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='khettara',
            name='date_diagnostic',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='khettara',
            name='defaut_ouvrage',
            field=models.TextField(blank=True, default='', help_text='Texte libre sur les défauts observés'),
        ),
        migrations.AddField(
            model_name='khettara',
            name='saisi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_saisis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='khettara',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='murprotection',
            name='date_diagnostic',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='murprotection',
            name='defaut_ouvrage',
            field=models.TextField(blank=True, default='', help_text='Texte libre sur les défauts observés'),
        ),
        migrations.AddField(
            model_name='murprotection',
            name='saisi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_saisis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='murprotection',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seguias',
            name='date_diagnostic',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='seguias',
            name='defaut_ouvrage',
            field=models.TextField(blank=True, default='', help_text='Texte libre sur les défauts observés'),
        ),
        migrations.AddField(
            model_name='seguias',
            name='saisi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_saisis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seguias',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seuil',
            name='date_diagnostic',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='seuil',
            name='defaut_ouvrage',
            field=models.TextField(blank=True, default='', help_text='Texte libre sur les défauts observés'),
        ),
        migrations.AddField(
            model_name='seuil',
            name='saisi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_saisis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seuil',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='barrageretenue',
            name='etat_construction_fonctionnement',
            field=models.TextField(blank=True, help_text='Texte libre'),
        ),
        migrations.AlterField(
            model_name='foragepuits',
            name='etat_construction_fonctionnement',
            field=models.TextField(blank=True, help_text='Texte libre'),
        ),
        migrations.AlterField(
            model_name='khettara',
            name='etat_construction_fonctionnement',
            field=models.TextField(blank=True, help_text='Texte libre'),
        ),
        migrations.AlterField(
            model_name='murprotection',
            name='etat_construction',
            field=models.TextField(blank=True, help_text='Texte libre'),
        ),
        migrations.AlterField(
            model_name='seguias',
            name='etat',
            field=models.TextField(blank=True, help_text='Texte libre'),
        ),
        migrations.AlterField(
            model_name='seuil',
            name='etat_construction_fonctionnement',
            field=models.TextField(blank=True, help_text='Texte libre'),
        ),
    ]
