# Generated by Django 6.0.4 on 2026-05-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0016_refactor_corrections_globales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sguiaassocie_ouvragetete',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
