# Generated by Django 6.0.4 on 2026-05-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0016_assolement_culture_choices'),
        ('diagnostic', '0017_alter_sguiaassocie_ouvragetete_id'),
    ]

    operations = [
    ]
