# Generated by Django 6.0.4 on 2026-05-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0019_assolement_unite_rendement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assolement',
            name='rendement',
            field=models.FloatField(blank=True, help_text='Rendement', null=True),
        ),
    ]
