# Generated by Django 6.0.4 on 2026-05-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0020_alter_assolement_rendement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assolement',
            name='culture',
            field=models.CharField(choices=[('Abricot', 'Abricot'), ('Agrumes', 'Agrumes'), ('Amande', 'Amande'), ('Betterave', 'Betterave'), ('Blé', 'Blé'), ('Carotte', 'Carotte'), ('Citron', 'Citron'), ('Clémentine', 'Clémentine'), ('Cumin', 'Cumin'), ('Datte', 'Datte'), ('Figue', 'Figue'), ('Grenade', 'Grenade'), ('Luzerne', 'Luzerne'), ('Mandarine', 'Mandarine'), ('Menthe', 'Menthe'), ('Mûre', 'Mûre'), ('Noix', 'Noix'), ('Oignon', 'Oignon'), ('Olive', 'Olive'), ('Orange', 'Orange'), ('Orge', 'Orge'), ('Pastèque', 'Pastèque'), ('Peche', 'Peche'), ('Piment', 'Piment'), ('Pois', 'Pois'), ('Pomme', 'Pomme'), ('PommeTerre', 'Pomme de terre'), ('Raisin', 'Raisin'), ('Rose', 'Rose'), ('Safran', 'Safran'), ('Tomate', 'Tomate')], max_length=100),
        ),
    ]
