# Generated by Django 6.0.4 on 2026-05-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0024_seguia_forme_diametre'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimetre',
            name='et0_mm_jour',
            field=models.FloatField(blank=True, help_text='Évapotranspiration de référence en mm par jour — utilisée par le module efficiences', null=True, verbose_name='ET0 (mm/jour)'),
        ),
        migrations.AddField(
            model_name='seguias',
            name='date_dernier_calcul',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date du dernier calcul d'efficience"),
        ),
        migrations.AddField(
            model_name='seguias',
            name='efficience_calculee',
            field=models.FloatField(blank=True, help_text='Efficience du tronçon en % issue du dernier calcul', null=True, verbose_name='Efficience calculée (%)'),
        ),
        migrations.AddField(
            model_name='seguias',
            name='perte_infiltration_m3s',
            field=models.FloatField(blank=True, help_text='Dernière perte par infiltration calculée (Davis & Wilson)', null=True, verbose_name='Perte par infiltration (m³/s)'),
        ),
        migrations.AddField(
            model_name='seguias',
            name='perte_vaporisation_m3s',
            field=models.FloatField(blank=True, help_text='Dernière perte par évaporation calculée (forcée à 0 pour les dalots)', null=True, verbose_name='Perte par évaporation (m³/s)'),
        ),
    ]
