# Generated by Django 6.0.4 on 2026-06-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0028_troncon_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tronconseguia',
            name='diametre',
            field=models.FloatField(blank=True, help_text='Requis pour la forme circulaire', null=True, verbose_name='Diamètre (m)'),
        ),
        migrations.AlterField(
            model_name='tronconseguia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
