# Generated by Django 6.0.4 on 2026-06-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0030_rename_statut_brouillon_to_non_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimetre',
            name='volume_annee_humide',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume — Année humide (m³)'),
        ),
        migrations.AddField(
            model_name='perimetre',
            name='volume_annee_normale',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume — Année normale (m³)'),
        ),
        migrations.AddField(
            model_name='perimetre',
            name='volume_annee_seche',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume — Année sèche (m³)'),
        ),
        migrations.AddField(
            model_name='perimetre',
            name='volume_excedent_deficit_humide',
            field=models.FloatField(blank=True, null=True, verbose_name='Excédent/Déficit — Année humide (m³)'),
        ),
        migrations.AddField(
            model_name='perimetre',
            name='volume_excedent_deficit_normale',
            field=models.FloatField(blank=True, null=True, verbose_name='Excédent/Déficit — Année normale (m³)'),
        ),
        migrations.AddField(
            model_name='perimetre',
            name='volume_excedent_deficit_seche',
            field=models.FloatField(blank=True, null=True, verbose_name='Excédent/Déficit — Année sèche (m³)'),
        ),
        migrations.AlterField(
            model_name='barrageretenue',
            name='statut',
            field=models.CharField(choices=[('non_valide', 'Non valide'), ('valide', 'Validé')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='foragepuits',
            name='statut',
            field=models.CharField(choices=[('non_valide', 'Non valide'), ('valide', 'Validé')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='khettara',
            name='statut',
            field=models.CharField(choices=[('non_valide', 'Non valide'), ('valide', 'Validé')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='murprotection',
            name='statut',
            field=models.CharField(choices=[('non_valide', 'Non valide'), ('valide', 'Validé')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='perimetre',
            name='statut',
            field=models.CharField(choices=[('non_valide', 'Non valide'), ('valide', 'Validé')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='priselocale',
            name='statut',
            field=models.CharField(choices=[('non_valide', 'Non valide'), ('valide', 'Validé')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='seuil',
            name='statut',
            field=models.CharField(choices=[('non_valide', 'Non valide'), ('valide', 'Validé')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='tronconseguia',
            name='statut',
            field=models.CharField(choices=[('non_valide', 'Non valide'), ('valide', 'Validé')], default='brouillon', max_length=20),
        ),
    ]
