# Generated by Django 6.0.4 on 2026-06-09 15:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0032_fix_geometry_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='perimetre',
            name='geometrie',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Géométrie (polygone du périmètre)'),
        ),
    ]
