# Generated by Django 6.0.4 on 2026-06-10 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostic', '0033_perimetre_add_geometrie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('type_requete', models.CharField(choices=[('plateforme', 'Signalement plateforme'), ('acces', "Demande d'utilisation / accès"), ('perimetre', 'Requête périmètre agricole')], max_length=20, verbose_name='Type de requête')),
                ('sous_type', models.CharField(blank=True, choices=[('PROB-01', "Rupture / brèche d'ouvrage"), ('PROB-02', 'Fuite ou colmatage de canal'), ('PROB-03', 'Panne de pompe / forage'), ('PROB-04', 'Tarissement ou débit insuffisant'), ('PROB-05', "Conflit de tour d'eau"), ('PROB-06', 'Déficit hydrique critique (sécheresse)'), ('PROB-07', 'Détérioration suite à crue'), ('PROB-08', 'Obstruction par sédiments / dépôts'), ('PROB-09', 'Vandalisme ou intrusion'), ('PROB-10', 'Autre problème terrain')], max_length=10, null=True, verbose_name='Sous-type')),
                ('description', models.TextField(verbose_name='Description')),
                ('urgence', models.CharField(choices=[('faible', 'Faible — aucun risque immédiat'), ('normale', 'Normale — à traiter sous 5 jours'), ('haute', 'Haute — à traiter sous 48 h'), ('critique', 'Critique — intervention immédiate requise')], default='normale', max_length=10, verbose_name='Urgence')),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('en_cours', 'En cours de traitement'), ('en_attente', "En attente d'informations complémentaires"), ('traitee', 'Traitée'), ('cloturee', 'Clôturée'), ('rejetee', 'Rejetée')], default='soumise', max_length=15, verbose_name='Statut')),
                ('type_emetteur', models.CharField(choices=[('auea', 'Responsable AUEA'), ('agriculteur', 'Agriculteur / Fellah'), ('agent_ormva', 'Agent ORMVA'), ('chef_secteur', 'Chef de secteur ORMVA'), ('garde_hydraulique', 'Garde hydraulique'), ('commune', 'Représentant de commune'), ('bureau_etudes', "Bureau d'études / Consultant"), ('ayant_droit_khettara', 'Actionnaire de khettara'), ('autre', 'Autre')], max_length=25, verbose_name='Profil émetteur')),
                ('nom_emetteur', models.CharField(blank=True, max_length=150, verbose_name='Nom (si non connecté)')),
                ('contact_emetteur', models.CharField(blank=True, max_length=150, verbose_name='Contact (email ou tél.)')),
                ('organisation', models.CharField(blank=True, max_length=200, verbose_name='Organisation / communauté')),
                ('ouvrage_type', models.CharField(blank=True, choices=[('seuil', 'Seuil'), ('mur_protection', 'Mur de protection'), ('seguia', 'Séguia'), ('barrage', 'Barrage'), ('khettara', 'Khettara'), ('forage', 'Forage / Puits'), ('prise_locale', 'Prise locale')], max_length=20, null=True, verbose_name="Type d'ouvrage")),
                ('ouvrage_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID ouvrage')),
                ('reponse', models.TextField(blank=True, verbose_name='Réponse officielle')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('date_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requetes_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assignée à')),
                ('emetteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requetes_emises', to=settings.AUTH_USER_MODEL, verbose_name='Émetteur (compte)')),
                ('perimetre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requetes', to='diagnostic.perimetre', verbose_name='Périmètre concerné')),
            ],
            options={
                'verbose_name': 'Requête',
                'verbose_name_plural': 'Requêtes',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointeRequete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='doleances/pj/%Y/%m/')),
                ('nom_original', models.CharField(max_length=255)),
                ('taille_ko', models.PositiveIntegerField(verbose_name='Taille (Ko)')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='doleances.requete')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_precedent', models.CharField(max_length=15, verbose_name='Statut précédent')),
                ('statut_nouveau', models.CharField(max_length=15, verbose_name='Nouveau statut')),
                ('commentaire', models.CharField(blank=True, max_length=500, verbose_name='Commentaire')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='doleances.requete')),
            ],
            options={
                'verbose_name': 'Historique statut',
                'verbose_name_plural': 'Historiques statuts',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireRequete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('interne', models.BooleanField(default=False, verbose_name='Commentaire interne (staff uniquement)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='doleances.requete')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['date_creation'],
            },
        ),
    ]
