# Generated by Django 6.0.4 on 2026-05-21 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostic', '0025_perimetre_et0_mm_jour_seguias_date_dernier_calcul_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Efficience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ouvrage_tete_type', models.CharField(choices=[('seuil', 'Seuil'), ('prise_locale', 'Prise locale'), ('khettara', 'Khettara'), ('forage_puits', 'Forage / Puits'), ('barrage_retenue', 'Barrage de retenue')], max_length=30)),
                ('ouvrage_tete_id', models.PositiveIntegerField(help_text="Identifiant de l'ouvrage de tête (selon le type)")),
                ('efficience_principale', models.FloatField(blank=True, help_text='Efficience moyenne pondérée des tronçons principaux (%)', null=True)),
                ('efficience_secondaire', models.FloatField(blank=True, help_text='Efficience moyenne pondérée des tronçons secondaires (%)', null=True)),
                ('efficience_tertiaire', models.FloatField(blank=True, help_text='Efficience moyenne pondérée des tronçons tertiaires (%)', null=True)),
                ('efficience_globale', models.FloatField(help_text='Efficience globale du réseau amont (%) — produit en cascade')),
                ('nb_troncons_principaux', models.PositiveSmallIntegerField(default=0)),
                ('nb_troncons_secondaires', models.PositiveSmallIntegerField(default=0)),
                ('nb_troncons_tertiaires', models.PositiveSmallIntegerField(default=0)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('operateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='efficiences_calculees', to=settings.AUTH_USER_MODEL)),
                ('perimetre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efficiences', to='diagnostic.perimetre')),
            ],
            options={
                'verbose_name': 'Efficience de réseau',
                'verbose_name_plural': 'Efficiences de réseaux',
                'ordering': ['-date_calcul'],
                'indexes': [models.Index(fields=['perimetre', 'ouvrage_tete_type', 'ouvrage_tete_id'], name='efficiences_perimet_fb8192_idx')],
            },
        ),
    ]
