# Generated by Django 6.0.4 on 2026-05-08 09:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Besions_Ressources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationclimatique',
            name='perimetre',
        ),
        migrations.AddField(
            model_name='stationclimatique',
            name='geometrie',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Géométrie (point)'),
        ),
        migrations.AddField(
            model_name='stationclimatique',
            name='x',
            field=models.FloatField(blank=True, null=True, verbose_name='X (Nord Maroc, m)'),
        ),
        migrations.AddField(
            model_name='stationclimatique',
            name='y',
            field=models.FloatField(blank=True, null=True, verbose_name='Y (Nord Maroc, m)'),
        ),
    ]
