# Generated by Django 6.0.4 on 2026-05-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Besions_Ressources', '0003_kc_kr_culture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kc_kr_culture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
