# Generated by Django 6.0.4 on 2026-05-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Besions_Ressources', '0008_ouvrage_params_et_autre_ressource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autreressource',
            name='apports_mensuels_humide',
            field=models.JSONField(blank=True, null=True, verbose_name='Apports mensuels année humide (m³, Sep→Aoû)'),
        ),
        migrations.AlterField(
            model_name='autreressource',
            name='apports_mensuels_normale',
            field=models.JSONField(blank=True, null=True, verbose_name='Apports mensuels année normale (m³, Sep→Aoû)'),
        ),
        migrations.AlterField(
            model_name='autreressource',
            name='apports_mensuels_seche',
            field=models.JSONField(blank=True, null=True, verbose_name='Apports mensuels année sèche (m³, Sep→Aoû)'),
        ),
        migrations.AlterField(
            model_name='bilanouvrageassocie',
            name='apports_mensuels_humide',
            field=models.JSONField(blank=True, null=True, verbose_name='Apports mensuels année humide (m³, Sep→Aoû)'),
        ),
        migrations.AlterField(
            model_name='bilanouvrageassocie',
            name='apports_mensuels_normale',
            field=models.JSONField(blank=True, null=True, verbose_name='Apports mensuels année normale (m³, Sep→Aoû)'),
        ),
        migrations.AlterField(
            model_name='bilanouvrageassocie',
            name='apports_mensuels_seche',
            field=models.JSONField(blank=True, null=True, verbose_name='Apports mensuels année sèche (m³, Sep→Aoû)'),
        ),
    ]
