# Generated by Django 6.0.4 on 2026-05-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Besions_Ressources', '0010_remove_bilanouvrageassocie_debit_aval_m3s_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilanbesoinressources',
            name='resultats_bilan_seche',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
