# Generated by Django 6.0.4 on 2026-06-04 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Besions_Ressources', '0014_bilanouvrage_troncon_vers_tronconseguia'),
        ('diagnostic', '0029_alter_tronconseguia_diametre_alter_tronconseguia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanouvrageassocie',
            name='troncon_amenee_2',
            field=models.ForeignKey(blank=True, help_text="2e tronçon d'amenée (seuil uniquement, optionnel)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilans_ouvrages_secondaire', to='diagnostic.tronconseguia', verbose_name="Tronçon d'amenée (2)"),
        ),
    ]
