# Generated by Django 6.0.4 on 2026-06-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Besions_Ressources', '0016_bilanbesoinressources_est_valide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kc_kr_culture',
            name='nom',
            field=models.CharField(choices=[('Abricot', 'Abricot'), ('Agrumes', 'Agrumes'), ('Amande', 'Amande'), ('Betterave', 'Betterave'), ('Blé', 'Blé'), ('Carotte', 'Carotte'), ('Citron', 'Citron'), ('Clémentine', 'Clémentine'), ('Cumin', 'Cumin'), ('Datte', 'Datte'), ('Figue', 'Figue'), ('Grenade', 'Grenade'), ('Luzerne', 'Luzerne'), ('Mais', 'Maïs'), ('Mandarine', 'Mandarine'), ('Menthe', 'Menthe'), ('Mûre', 'Mûre'), ('Noix', 'Noix'), ('Oignon', 'Oignon'), ('Olive', 'Olive'), ('Orange', 'Orange'), ('Orge', 'Orge'), ('Pastèque', 'Pastèque'), ('Peche', 'Peche'), ('Piment', 'Piment'), ('Pois', 'Pois'), ('Pomme', 'Pomme'), ('PommeTerre', 'Pomme de terre'), ('Raisin', 'Raisin'), ('Rose', 'Rose'), ('Safran', 'Safran'), ('Tomate', 'Tomate')], max_length=100, unique=True, verbose_name='Nom de culture'),
        ),
    ]
