# Generated by Django 6.0.4 on 2026-06-04 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0003_province_population_rurale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequeteNommee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('couche', models.CharField(max_length=100)),
                ('expression', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requetes_nommees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requête nommée',
                'verbose_name_plural': 'Requêtes nommées',
                'unique_together': {('utilisateur', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='StyleCouche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_couche', models.CharField(max_length=100)),
                ('nom_style', models.CharField(max_length=100)),
                ('parametres', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles_couche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Style de couche',
                'verbose_name_plural': 'Styles de couches',
                'unique_together': {('utilisateur', 'nom_couche', 'nom_style')},
            },
        ),
    ]
