# Generated by Django 6.0.4 on 2026-06-10 15:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0004_stylecouche_requete_nommee'),
    ]

    operations = [
        migrations.CreateModel(
            name='BassinVersant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('superficie_km2', models.FloatField(verbose_name='Superficie (km²)')),
                ('perimetre_km', models.FloatField(default=0.0, verbose_name='Périmètre (km)')),
                ('altitude_min', models.FloatField(verbose_name='Altitude minimale (m)')),
                ('altitude_max', models.FloatField(verbose_name='Altitude maximale (m)')),
                ('altitude_exutoire', models.FloatField(verbose_name='Altitude exutoire (m)')),
                ('thalweg_km', models.FloatField(verbose_name='Longueur thalweg principal (km)')),
                ('precipitations_annuelles_mm', models.FloatField(blank=True, null=True, verbose_name='Précipitations annuelles (mm/an)')),
                ('evapotranspiration_annuelle_mm', models.FloatField(blank=True, null=True, verbose_name='Évapotranspiration annuelle (mm/an)')),
                ('geometrie', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Géométrie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bassin versant (Carte)',
                'verbose_name_plural': 'Bassins versants (Carte)',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ReseauHydrographique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comid', models.IntegerField(verbose_name='COMID (identifiant tronçon)')),
                ('sorder', models.IntegerField(verbose_name='Ordre de Strahler')),
                ('geometrie', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Géométrie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bassin_versant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troncons', to='carte.bassinversant', verbose_name='Bassin versant')),
            ],
            options={
                'verbose_name': 'Réseau hydrographique (Carte)',
                'verbose_name_plural': 'Réseaux hydrographiques (Carte)',
                'indexes': [models.Index(fields=['bassin_versant'], name='carte_resea_bassin__113b15_idx'), models.Index(fields=['sorder'], name='carte_resea_sorder_fe2a83_idx')],
            },
        ),
    ]
