# Generated by Django 6.0.4 on 2026-06-13 18:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0005_bassinversant_reseauhydrographique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReseauOuvrageTeteGuir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_code', models.IntegerField(blank=True, null=True, verbose_name='Grid code')),
                ('geometrie', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Géométrie (polyligne)')),
            ],
            options={
                'verbose_name': 'Réseau ouvrage de tête — Guir',
                'verbose_name_plural': 'Réseau ouvrage de tête — Guir',
            },
        ),
        migrations.CreateModel(
            name='ReseauOuvrageTeteMaider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_code', models.IntegerField(blank=True, null=True, verbose_name='Grid code')),
                ('geometrie', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Géométrie (polyligne)')),
            ],
            options={
                'verbose_name': 'Réseau ouvrage de tête — Maïder',
                'verbose_name_plural': 'Réseau ouvrage de tête — Maïder',
            },
        ),
        migrations.CreateModel(
            name='ReseauOuvrageTeteMoulouya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_code', models.IntegerField(blank=True, null=True, verbose_name='Grid code')),
                ('geometrie', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Géométrie (polyligne)')),
            ],
            options={
                'verbose_name': 'Réseau ouvrage de tête — Moulouya',
                'verbose_name_plural': 'Réseau ouvrage de tête — Moulouya',
            },
        ),
        migrations.CreateModel(
            name='ReseauOuvrageTeteRheris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_code', models.IntegerField(blank=True, null=True, verbose_name='Grid code')),
                ('geometrie', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Géométrie (polyligne)')),
            ],
            options={
                'verbose_name': 'Réseau ouvrage de tête — Rhéris',
                'verbose_name_plural': 'Réseau ouvrage de tête — Rhéris',
            },
        ),
        migrations.CreateModel(
            name='ReseauOuvrageTeteZiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_code', models.IntegerField(blank=True, null=True, verbose_name='Grid code')),
                ('geometrie', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Géométrie (polyligne)')),
            ],
            options={
                'verbose_name': 'Réseau ouvrage de tête — Ziz',
                'verbose_name_plural': 'Réseau ouvrage de tête — Ziz',
            },
        ),
    ]
