# Generated by Django 6.0.4 on 2026-06-09 09:32

import django.core.validators
import django.db.models.deletion
import plan_action.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carte', '0004_stylecouche_requete_nommee'),
        ('diagnostic', '0032_fix_geometry_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('ACT-01', 'Réhabilitation de séguias'), ('ACT-02', 'Construction de séguias neuves'), ('ACT-03', 'Construction de seuils de dérivation'), ('ACT-04', 'Réhabilitation de khettaras'), ('ACT-05', 'Construction / réhabilitation de barrages collinaires'), ('ACT-06', "Aménagement de prises d'eau locales"), ('ACT-07', 'Renforcement de murs de protection'), ('ACT-08', 'Entretien et curage de canaux'), ('ACT-09', 'Réhabilitation de forages / puits'), ('ACT-10', 'Irrigation localisée (goutte à goutte)'), ('ACT-11', 'Planage et nivellement de parcelles'), ('ACT-12', "Aménagement de pistes d'accès"), ('ACT-13', 'Protection contre les crues (digues, épis)'), ('ACT-14', 'Étude technique préalable (APD / APS)'), ('ACT-15', 'Autre')], max_length=10, verbose_name="Type d'action")),
                ('description', models.TextField(verbose_name='Description')),
                ('budget_prevu', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Budget prévu (MAD)')),
                ('superficie_concernee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Superficie concernée (ha)')),
                ('longueur_prevue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Longueur prévue (ml)')),
                ('statut', models.CharField(choices=[('programme', 'Programmé'), ('en_cours', 'En cours'), ('realise', 'Réalisé'), ('annule', 'Annulé')], default='programme', max_length=20, verbose_name='Statut')),
                ('priorite', models.IntegerField(choices=[(1, 'Haute'), (2, 'Moyenne'), (3, 'Basse')], default=2, verbose_name='Priorité')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carte.commune', verbose_name='Commune')),
                ('perimetre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.perimetre', verbose_name='Périmètre (optionnel)')),
            ],
            options={
                'verbose_name': 'Action du plan',
                'verbose_name_plural': 'Actions du plan',
                'ordering': ['priorite', 'type_action'],
            },
        ),
        migrations.CreateModel(
            name='CalendrierIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_prevue', models.DateField(verbose_name='Date de début prévue')),
                ('date_fin_prevue', models.DateField(verbose_name='Date de fin prévue')),
                ('mode_realisation', models.CharField(choices=[('etude_interne_ormva', 'Étude interne ORMVA'), ('marche_public', 'Marché public'), ('appel_manifestation_interet', "Appel à manifestation d'intérêt"), ('regie', 'Régie')], max_length=50, verbose_name='Mode de réalisation')),
                ('statut_calendrier', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('cloture', 'Clôturé')], default='brouillon', max_length=20, verbose_name='Statut du calendrier')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendrier', to='plan_action.actionplan', verbose_name='Action du plan')),
                ('chef_projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendriers_chef', to=settings.AUTH_USER_MODEL, verbose_name='Chef de projet')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendriers_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': "Calendrier d'intervention",
                'verbose_name_plural': "Calendriers d'intervention",
            },
        ),
        migrations.CreateModel(
            name='PlanAmenagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2050)], verbose_name='Année')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('budget_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Budget total (MAD)')),
                ('source_financement', models.CharField(choices=[('budget_etat', 'Budget État'), ('feader', 'FEADER'), ('collectivite', 'Collectivité'), ('partenariat', 'Partenariat'), ('autre', 'Autre')], max_length=50, verbose_name='Source de financement')),
                ('statut', models.CharField(choices=[('en_preparation', 'En préparation'), ('publie', 'Publié'), ('archive', 'Archivé')], default='en_preparation', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': "Plan d'aménagement",
                'verbose_name_plural': "Plans d'aménagement",
                'ordering': ['-annee'],
            },
        ),
        migrations.AddField(
            model_name='actionplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='plan_action.planamenagement', verbose_name="Plan d'aménagement"),
        ),
        migrations.CreateModel(
            name='SuiviAvancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rapport', models.DateField(verbose_name='Date du rapport')),
                ('avancement_pct', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Avancement (%)')),
                ('etat_bloc', models.CharField(choices=[('conforme', 'Conforme'), ('retard', 'En retard'), ('bloque', 'Bloqué'), ('termine', 'Terminé')], max_length=20, verbose_name='État')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_prochaine_echeance', models.DateField(blank=True, null=True, verbose_name='Prochaine échéance')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapports_suivi', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Rapport de suivi',
                'verbose_name_plural': 'Rapports de suivi',
                'ordering': ['-date_rapport'],
            },
        ),
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('pv_attachement', "PV d'attachement"), ('pv_reception', 'PV de réception'), ('photo_chantier', 'Photo de chantier'), ('rapport_etude', "Rapport d'étude"), ('note_administrative', 'Note administrative'), ('autre', 'Autre')], max_length=30, verbose_name='Type de pièce')),
                ('fichier', models.FileField(upload_to=plan_action.models.piece_upload_path, verbose_name='Fichier')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('date_document', models.DateField(blank=True, null=True, verbose_name='Date du document')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('uploade_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces_uploadees', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='plan_action.suiviavancement', verbose_name='Rapport de suivi')),
            ],
            options={
                'verbose_name': 'Pièce justificative',
                'verbose_name_plural': 'Pièces justificatives',
            },
        ),
        migrations.CreateModel(
            name='TacheIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_tache', models.CharField(max_length=20, verbose_name='Code tâche')),
                ('nom_tache', models.CharField(max_length=200, verbose_name='Nom de la tâche')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut_prevue', models.DateField(verbose_name='Date de début prévue')),
                ('date_fin_prevue', models.DateField(verbose_name='Date de fin prévue')),
                ('duree_prevue', models.PositiveIntegerField(verbose_name='Durée prévue (jours calendaires)')),
                ('type_suivi', models.CharField(choices=[('suivi_travaux', 'Suivi travaux'), ('suivi_etude', 'Suivi étude'), ('suivi_administratif', 'Suivi administratif'), ('realisation_etude_interne', 'Réalisation étude interne')], max_length=30, verbose_name='Type de suivi')),
                ('statut_tache', models.CharField(choices=[('non_demarree', 'Non démarrée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('bloquee', 'Bloquée')], default='non_demarree', max_length=20, verbose_name='Statut de la tâche')),
                ('calendrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='plan_action.calendrierintervention', verbose_name='Calendrier')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taches_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('taches_anterieures', models.ManyToManyField(blank=True, to='plan_action.tacheintervention', verbose_name='Tâches antérieures (dépendances FS)')),
            ],
            options={
                'verbose_name': "Tâche d'intervention",
                'verbose_name_plural': "Tâches d'intervention",
                'ordering': ['code_tache'],
                'unique_together': {('calendrier', 'code_tache')},
            },
        ),
        migrations.AddField(
            model_name='suiviavancement',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='plan_action.tacheintervention', verbose_name='Tâche'),
        ),
    ]
