# Generated by Django 6.0.4 on 2026-04-23 22:11

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BassinVersant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('x_exutoire', models.FloatField(verbose_name='X exutoire')),
                ('y_exutoire', models.FloatField(verbose_name='Y exutoire')),
                ('surface', models.FloatField(verbose_name='Surface (km²)')),
                ('perimetre', models.FloatField(verbose_name='Périmètre (km)')),
                ('z_min', models.FloatField(verbose_name='Zmin (m)')),
                ('z_max', models.FloatField(verbose_name='Zmax (m)')),
                ('thalweg', models.FloatField(verbose_name='Longueur du thalweg (km)')),
                ('ouvrage_en_tete', models.CharField(blank=True, max_length=255, verbose_name='Ouvrage en tête')),
                ('geometrie', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Géométrie')),
            ],
            options={
                'verbose_name': 'Bassin Versant',
                'verbose_name_plural': 'Bassins Versants',
            },
        ),
        migrations.CreateModel(
            name='StationHydrometrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('x', models.FloatField(verbose_name='X')),
                ('y', models.FloatField(verbose_name='Y')),
                ('annees', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, verbose_name='Années')),
                ('qjmax', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, verbose_name='Qjmax observées (m³/s)')),
                ('qjmax_t10', models.FloatField(blank=True, null=True, verbose_name='Qjmax T=10 ans (m³/s)')),
                ('qjmax_t20', models.FloatField(blank=True, null=True, verbose_name='Qjmax T=20 ans (m³/s)')),
                ('qjmax_t50', models.FloatField(blank=True, null=True, verbose_name='Qjmax T=50 ans (m³/s)')),
                ('qjmax_t100', models.FloatField(blank=True, null=True, verbose_name='Qjmax T=100 ans (m³/s)')),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Géométrie (point)')),
            ],
            options={
                'verbose_name': 'Station Hydrométrique',
                'verbose_name_plural': 'Stations Hydrométriques',
            },
        ),
        migrations.CreateModel(
            name='StationPluviometrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('x', models.FloatField(verbose_name='X')),
                ('y', models.FloatField(verbose_name='Y')),
                ('annees', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, verbose_name='Années')),
                ('pjmax', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, verbose_name='Pjmax observées (mm)')),
                ('pjmax_t10', models.FloatField(blank=True, null=True, verbose_name='Pjmax T=10 ans (mm)')),
                ('pjmax_t20', models.FloatField(blank=True, null=True, verbose_name='Pjmax T=20 ans (mm)')),
                ('pjmax_t50', models.FloatField(blank=True, null=True, verbose_name='Pjmax T=50 ans (mm)')),
                ('pjmax_t100', models.FloatField(blank=True, null=True, verbose_name='Pjmax T=100 ans (mm)')),
                ('hauteur_moyenne', models.FloatField(verbose_name='Hauteur moyenne annuelle (mm)')),
                ('grad_exp_pluie', models.FloatField(verbose_name='Gradient exponentiel de pluie')),
                ('geometrie', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Géométrie (polygone)')),
            ],
            options={
                'verbose_name': 'Station Pluviométrique',
                'verbose_name_plural': 'Stations Pluviométriques',
            },
        ),
        migrations.CreateModel(
            name='ReseauHydrographique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, verbose_name="Nom du cours d'eau")),
                ('geometrie', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Géométrie (polyligne)')),
                ('bassin_versant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseau_hydrographique', to='analyse_hydrologique.bassinversant', verbose_name='Bassin versant')),
            ],
            options={
                'verbose_name': 'Réseau Hydrographique',
                'verbose_name_plural': 'Réseaux Hydrographiques',
            },
        ),
        migrations.CreateModel(
            name='ResultatAnalyseHydrologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_analyse', models.DateTimeField(auto_now_add=True, verbose_name="Date d'analyse")),
                ('methode', models.CharField(blank=True, choices=[('rationnelle', 'Méthode Rationnelle'), ('socose', 'Méthode SOCOSE'), ('montana', 'Formule de Montana'), ('gradex', 'Méthode du Gradex'), ('autre', 'Autre')], max_length=50, verbose_name='Méthode utilisée')),
                ('qcrue_t10', models.FloatField(blank=True, null=True, verbose_name='Q crue T=10 ans (m³/s)')),
                ('qcrue_t20', models.FloatField(blank=True, null=True, verbose_name='Q crue T=20 ans (m³/s)')),
                ('qcrue_t50', models.FloatField(blank=True, null=True, verbose_name='Q crue T=50 ans (m³/s)')),
                ('qcrue_t100', models.FloatField(blank=True, null=True, verbose_name='Q crue T=100 ans (m³/s)')),
                ('temps_concentration', models.FloatField(blank=True, null=True, verbose_name='Temps de concentration (h)')),
                ('coefficient_ruissellement', models.FloatField(blank=True, null=True, verbose_name='Coefficient de ruissellement')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('conclusions', models.TextField(blank=True, verbose_name='Conclusions et recommandations')),
                ('bassin_versant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_analyse', to='analyse_hydrologique.bassinversant', verbose_name='Bassin versant')),
                ('operateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_hydrologiques', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': "Résultat d'Analyse Hydrologique",
                'verbose_name_plural': "Résultats d'Analyses Hydrologiques",
                'ordering': ['-date_analyse'],
            },
        ),
        migrations.CreateModel(
            name='CoefficientMontana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a10', models.FloatField(blank=True, null=True, verbose_name='a  T=10 ans')),
                ('a20', models.FloatField(blank=True, null=True, verbose_name='a  T=20 ans')),
                ('a50', models.FloatField(blank=True, null=True, verbose_name='a  T=50 ans')),
                ('a100', models.FloatField(blank=True, null=True, verbose_name='a  T=100 ans')),
                ('b10', models.FloatField(blank=True, null=True, verbose_name='b  T=10 ans')),
                ('b20', models.FloatField(blank=True, null=True, verbose_name='b  T=20 ans')),
                ('b50', models.FloatField(blank=True, null=True, verbose_name='b  T=50 ans')),
                ('b100', models.FloatField(blank=True, null=True, verbose_name='b  T=100 ans')),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients_montana', to='analyse_hydrologique.stationpluviometrique', verbose_name='Station pluviométrique')),
            ],
            options={
                'verbose_name': 'Coefficient de Montana',
                'verbose_name_plural': 'Coefficients de Montana',
            },
        ),
    ]
