# Generated by Django 6.0.4 on 2026-04-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_hydrologique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationhydrometrique',
            name='superficie_bv_jaugee',
            field=models.FloatField(blank=True, null=True, verbose_name='Superficie BV jaugé (km²)'),
        ),
    ]
