# Generated by Django 6.0.4 on 2026-05-08 08:56

import django.contrib.postgres.fields
from django.db import migrations, models

_JOURS_PAR_MOIS = [30, 31, 30, 31, 31, 28, 31, 30, 31, 30, 31, 31]


def _init_freq_defaults(apps, schema_editor):
    StationHydrometrique = apps.get_model('analyse_hydrologique', 'StationHydrometrique')
    for station in StationHydrometrique.objects.all():
        updated = False
        if not station.frequences_mensuelles_annee_normale:
            station.frequences_mensuelles_annee_normale = list(_JOURS_PAR_MOIS)
            updated = True
        if not station.frequences_mensuelles_annee_humide:
            station.frequences_mensuelles_annee_humide = list(_JOURS_PAR_MOIS)
            updated = True
        if updated:
            station.save(update_fields=[
                'frequences_mensuelles_annee_normale',
                'frequences_mensuelles_annee_humide',
            ])


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_hydrologique', '0005_stationhydrometrique_debits_mensuels'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationhydrometrique',
            name='debits_mensuels_annee_normale',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=12, verbose_name='Débits mensuels année normale (m³/s, Sep→Aoû)'),
        ),
        migrations.AddField(
            model_name='stationhydrometrique',
            name='frequences_mensuelles_annee_humide',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=12, verbose_name='Fréquences mensuelles année humide (jours, Sep→Aoû)'),
        ),
        migrations.AddField(
            model_name='stationhydrometrique',
            name='frequences_mensuelles_annee_normale',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=12, verbose_name='Fréquences mensuelles année normale (jours, Sep→Aoû)'),
        ),
        migrations.AlterField(
            model_name='bassinversant',
            name='x_exutoire',
            field=models.FloatField(verbose_name='X exutoire (Nord Maroc, m)'),
        ),
        migrations.AlterField(
            model_name='bassinversant',
            name='y_exutoire',
            field=models.FloatField(verbose_name='Y exutoire (Nord Maroc, m)'),
        ),
        migrations.AlterField(
            model_name='stationhydrometrique',
            name='x',
            field=models.FloatField(verbose_name='X (Nord Maroc, m)'),
        ),
        migrations.AlterField(
            model_name='stationhydrometrique',
            name='y',
            field=models.FloatField(verbose_name='Y (Nord Maroc, m)'),
        ),
        migrations.AlterField(
            model_name='stationpluviometrique',
            name='x',
            field=models.FloatField(verbose_name='X (Nord Maroc, m)'),
        ),
        migrations.AlterField(
            model_name='stationpluviometrique',
            name='y',
            field=models.FloatField(verbose_name='Y (Nord Maroc, m)'),
        ),
        migrations.RunPython(_init_freq_defaults, migrations.RunPython.noop),
    ]
