# Generated by Django 6.0.4 on 2026-06-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_hydrologique', '0007_stationhydrometrique_annee_seche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseauhydrographique',
            name='bassin_versant',
        ),
        migrations.AddField(
            model_name='reseauhydrographique',
            name='grid_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Grid code'),
        ),
    ]
