# Generated by Django 6.0.4 on 2026-06-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_hydrologique', '0008_remove_reseauhydrographique_bassin_versant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseauhydrographique',
            name='nom',
        ),
    ]
