# Generated by Django 6.0.4 on 2026-06-03 11:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_hydrologique', '0009_remove_reseauhydrographique_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationhydrometrique',
            name='frequences_mensuelles_annee_humide',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=12, verbose_name='Fréquences mensuelles année humide (jours, Sep→Aoû)'),
        ),
        migrations.AlterField(
            model_name='stationhydrometrique',
            name='frequences_mensuelles_annee_normale',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=12, verbose_name='Fréquences mensuelles année normale (jours, Sep→Aoû)'),
        ),
        migrations.AlterField(
            model_name='stationhydrometrique',
            name='frequences_mensuelles_annee_seche',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=12, verbose_name='Fréquences mensuelles année sèche (jours, Sep→Aoû)'),
        ),
    ]
