# Generated by Django 6.0.4 on 2026-06-11 16:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_hydrologique', '0011_resultatanalysehydrologique_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationpluviometrique',
            name='geom_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Géométrie point (WGS84)'),
        ),
    ]
