# Generated by Django 6.0.4 on 2026-06-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_hydrologique', '0012_add_geom_point_stationpluvio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReseauHydrographique',
        ),
    ]
